### ISSUE TITLE
Cannot import multi-index Pandas DataFrame

### ISSUE THREAD

**Issue by rvernica** [Paradigm4/SciDB-Py#100]
Multi-index (multi-dimensional) Pandas DataFrames cannot be imported by the library, even if such DataFrames are exported by the library. Here is an example:
```python
>>> import scidbpy
>>> db = scidbpy.connect()
>>> db.afl.create_array('foo', '<x:int64 not null>[i=0:1; j=0:1]', True).eval(store=False)
>>> db.afl.build('foo', 'i + j').store('foo').eval(store=False)
>>> df = db.wrap_array('foo').todataframe()
>>> df
     x
i j   
0 0  0
  1  1
1 0  1
  1  2
>>> db.from_dataframe(df)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../scidbpy/interface.py", line 969, in from_dataframe
    **kwargs)
  File ".../scidbpy/interface.py", line 348, in new_array
    datashape = SciDBDataShape(shape, dtype, **kwargs)
  File ".../scidbpy/scidbarray.py", line 293, in __init__
    raise ValueError("length of dim_names should match "
ValueError: length of dim_names should match number of dimensions
```
If the DataFrame has a single index, it works fine:
```python
>>> db.afl.create_array('bar', '<x:int64 not null>[i=0:1]', True).eval(store=False)
>>> db.afl.build('bar', 'i').store('bar').eval(store=False)
>>> df = db.wrap_array('bar').todataframe()
>>> df
   x
i   
0  0
1  1
>>> db.from_dataframe(df)
SciDBArray()
```
---
* SciDB `16.9`
* SciDB-Py [0afda10](https://github.com/Paradigm4/SciDB-Py/tree/0afda10aa7987a993496668094cdb68cd4141321)
* Pandas `0.19.2`
* NumPy `1.11.0`

**Comment by rvernica** [comment]
Obsolete, multi-index (multi-dimensional) Pandas DataFrames are no longer supported.
