### ISSUE TITLE
Cannot wrap_array with auto chunking

### ISSUE THREAD

**Issue by rvernica** [Paradigm4/SciDB-Py#102]
If auto chunking is used the library cannot wrap the array. Here is an example:
```python
>>> import scidbpy
>>> db = scidbpy.connect()
>>> db.query('create array foo<x:int64>[i=0:0]')
>>> db.wrap_array('foo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...scidbpy/interface.py", line 307, in wrap_array
    datashape = SciDBDataShape.from_schema(schema)
  File "...scidbpy/scidbarray.py", line 393, in from_schema
    chunk_size=[int(d[4]) for d in dshapes],
ValueError: invalid literal for int() with base 10: '*'
```
The array schema is:
```python
# iquery --afl
AFL% show(foo);
{i} schema
{0} 'foo<x:int64> [i=0:0:0:*]'
```
---
* SciDB `16.9`
* SciDB-Py [0afda10](https://github.com/Paradigm4/SciDB-Py/tree/0afda10aa7987a993496668094cdb68cd4141321)

**Comment by rvernica** [comment]
Obsolete, `wrap_array` no longer available.
