### ISSUE TITLE
New version: error when using the double type

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/SciDB-Py#105]
Perhaps a type issue?

```Python
>>> iquery(scidb, "build(<val:int64>[i=1:10,10,0], random())", fetch=True)
array([((255, 358237803), 1), ((255, 142484295), 2),
       ((255, 1347983258), 3), ((255, 442093414), 4),
       ((255, 629485456), 5), ((255, 1605858031), 6),
       ((255, 1236363000), 7), ((255, 89663046), 8),
       ((255, 2128602764), 9), ((255, 1934565753), 10)], 
      dtype=[('val', [('null', 'u1'), ('val', '<i8')]), ('i', '<i8')])

>>> iquery(scidb, "build(<val:double>[i=1:10,10,0], random())", fetch=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "scidbpy/db.py", line 360, in iquery
    for (att, (off, sz)) in zip(sch.atts, meta)))
  File "scidbpy/db.py", line 360, in <genexpr>
    for (att, (off, sz)) in zip(sch.atts, meta)))
  File "scidbpy/schema.py", line 136, in frombytes
    buf, self.val_dtype, 1, offset + null_size)[0]
ValueError: offset must be non-negative and no greater than buffer length (170)
```

**Comment by rvernica** [comment]
Yes, indeed, a type issue. Thanks. Fixed.
```python
numpy.dtype.double.__name__ != 'double' # == 'float64'
```
