### ISSUE TITLE
Devel branch: error when running versions()

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/SciDB-Py#106]
```Python
>>> scidb = connect()
>>> iquery(scidb, "store(build(<val:double>[i=1:10,10,0], i), foo)")
>>> iquery(scidb, "versions(foo)", fetch=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/scidb/SciDB-Py/scidbpy/db.py", line 466, in iquery
    for (att, (off, sz)) in zip(sch.atts, meta)))
  File "/home/scidb/SciDB-Py/scidbpy/db.py", line 466, in <genexpr>
    for (att, (off, sz)) in zip(sch.atts, meta)))
  File "/home/scidb/SciDB-Py/scidbpy/schema.py", line 154, in frombytes
    buf, self.val_dtype, 1, offset + null_size)[0]
ValueError: offset must be non-negative and no greater than buffer length (24)
```

**Comment by rvernica** [comment]
What is the hash of your head? I could not reproduce it on the latest head:
```python
>>> scidb = connect()
>>> iquery(scidb, "store(build(<val:double>[i=1:10,10,0], i), foo)")
>>> iquery(scidb, "versions(foo)", fetch=True)
array([ (1, 1, b'\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\xacc\x18Y\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\xedc\x18Y\x00\x00\x00\x00')], 
      dtype=[('VersionNo', '<i8'), ('version_id', '<i8'), ('timestamp', 'O')])
```
Notice how the `timestamp` attribute is in byte-array format since it is not supported yet. 

I added a test for this use case in the test suite.
