### ISSUE TITLE
_sg not recognized as an operator

### ISSUE THREAD

**Issue by rvernica** [Paradigm4/SciDB-Py#117]
`_sg` is not recognized as an operator by SciDB-Py:
```python
>>> db.list
Operator(db=DB('http://localhost:8080', None, None, None, None), name='list', args=[])
>>> db._sg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rares/.local/lib/python3.6/site-packages/scidbpy/db.py", line 168, in __getattr__
    type(self), name))
AttributeError: 'DB' object has no attribute '_sg'
```
The reason is that `_sg` does not show up in the `list('oprators')` or `list('macros')` output:
```bash
$ iquery --afl --query "list('operators')" | grep sg
$ iquery --afl --query "list('macros')" | grep sg
```

**Comment by jmcq** [comment]
_sg is not intended to be used explicitly in queries.   It is inserted into
queries only as necessary, and its use beyond that is not supported.

**Comment by apoliakov** [comment]
@jmcq  - Jason and I were discussing relaxing that. Let's talk further.

**Comment by jmcq** [comment]
Talk to Jason about it if you would ... I'm greatly overbooked by Steve's
departure.

**Comment by apoliakov** [comment]
@rvernica: we'll do some pow-wowing internally but for now assume no changes from what we've previously discussed.

**Comment by rvernica** [comment]
Sure. The `_sg` operator can be used from SciDB-Py using the `iquery` function just fine.
