### ISSUE TITLE
Nesting rest server(using requests) with scidb-py leads to error

### ISSUE THREAD

**Issue by jrivers96** [Paradigm4/SciDB-Py#131]
The problem is described at the link below. It is a python requests problem, but perhaps there is a fix to put into SciDB-Py.  The error occurs 

https://stackoverflow.com/questions/23013220/max-retries-exceeded-with-url?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

```
Traceback (most recent call last):
  File "/bigdisk/miniconda3/envs/bunnies/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/bigdisk/miniconda3/envs/bunnies/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/bigdisk/miniconda3/envs/bunnies/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/bigdisk/miniconda3/envs/bunnies/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/bigdisk/miniconda3/envs/bunnies/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/bigdisk/miniconda3/envs/bunnies/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/development/POCmaterial/GSK/generated/python-flask-server/viz_server/run_viz_server.py", line 31, in retrieve_cube
    fstatus, files = aa.create_six_sides_from_z(db=ims.connect(), z=z , array_label=array_label,
  File "/bigdisk/miniconda3/envs/bunnies/lib/python3.4/site-packages/scidbpy/db.py", line 125, in __init__
    self._id = self._shim(Shim.new_session).text
  File "/bigdisk/miniconda3/envs/bunnies/lib/python3.4/site-packages/scidbpy/db.py", line 430, in _shim
    verify=self.verify)
  File "/bigdisk/miniconda3/envs/bunnies/lib/python3.4/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/bigdisk/miniconda3/envs/bunnies/lib/python3.4/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/bigdisk/miniconda3/envs/bunnies/lib/python3.4/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/bigdisk/miniconda3/envs/bunnies/lib/python3.4/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/bigdisk/miniconda3/envs/bunnies/lib/python3.4/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /new_session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff5613effd0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
INFO:werkzeug:127.0.0.1 - - [28/Mar/2018 22:52:56] "OPTIONS /api/retrieve_cube HTTP/1.1" 500 -
[2018-03-28 22:52:57,738] ERROR in app: Exception on /api/retrieve_cube [OPTIONS]
```

**Comment by jrivers96** [comment]
I had a function with: function_call(db=connect()).
