### ISSUE TITLE
Load datetime or datetimetz from numpy datetime64 using scidbpy.from_array()

### ISSUE THREAD

**Issue by lkrcal** [Paradigm4/SciDB-Py#83]
I have been trying to load datetime data into SciDB (14.12) using SciDB-Py (scidb_py-14.12.0) and numpy array.

At first, I encountered a problem, where the numpy.datetime64 has to be in [s] units.

```
>>> sdb.from_array(np.array([np.datetime64(datetime.strptime("1998072012", "%Y%m%d%H"))], dtype="datetime64"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/scidbpy/interface.py", line 863, in from_array
  File "build/bdist.linux-x86_64/egg/scidbpy/interface.py", line 348, in new_array
  File "build/bdist.linux-x86_64/egg/scidbpy/scidbarray.py", line 273, in __init__
  File "build/bdist.linux-x86_64/egg/scidbpy/scidbarray.py", line 125, in __init__
  File "build/bdist.linux-x86_64/egg/scidbpy/scidbarray.py", line 242, in _dtype_to_schema
  File "build/bdist.linux-x86_64/egg/scidbpy/scidbarray.py", line 64, in _sdb_type
TypeError: Numpy dtype has no SciDB equivalent: <M8[us]
```

So using [s] unit, I got another error when loading the binary data. All of the following snippets resulted in the same error:

```
>>> sdb.from_array(np.array([np.datetime64(datetime.strptime("1998072012", "%Y%m%d%H"))], dtype="datetime64[s]"))
>>> sdb.from_array(np.array([np.datetime64(datetime.strptime("1998072012", "%Y%m%d%H"))], dtype="datetime64[s]"))
>>> sdb.from_array(np.array([np.datetime64(datetime.strptime("1998072012", "%Y%m%d%H"), 's')], dtype="datetime64[s]"))
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/scidbpy/interface.py", line 865, in from_array
  File "build/bdist.linux-x86_64/egg/scidbpy/scidbarray.py", line 1019, in eval
  File "build/bdist.linux-x86_64/egg/scidbpy/interface.py", line 1662, in _execute_query
  File "build/bdist.linux-x86_64/egg/scidbpy/interface.py", line 1733, in _shim_execute_query
  File "build/bdist.linux-x86_64/egg/scidbpy/interface.py", line 1698, in _shim_urlopen
scidbpy.errors.SciDBQueryError: UserException in file: src/query/ops/input/InputArray.cpp function: moveNext line: 371
Error id: scidb::SCIDB_SE_IMPORT_ERROR::SCIDB_LE_FILE_IMPORT_FAILED
Error description: Import error. Import from file '/tmp/shim_input_buf_nFUK3b' (instance 0) to array 'py1101077901205_00007' failed at line 1, column 0, offset 0, value='(unreadable)': Failed to read file: 0.
```

SciDB tried to load the data into the following array. Instead of using datetime, it defaulted to datetimetz.

```
'py1101077901205_00007',47275,47275,'py1101077901205_00007<f0:datetimetz> [i0=0:0,1000,0]',true,false
```

I resorted to loading the datetime as int64 instead and then casting them to datetime in SciDB. But this somehow assumes the data is in my timezone, instead of UTC. Note that no timezone was provided and my intention here is still loading datetime (not datetimetz) in UTC.

```
>>> time.mktime(datetime.strptime("1998072012", "%Y%m%d%H").timetuple()
900907200.0
>>> datetime.fromtimestamp(time.mktime(datetime.strptime("1998072012", "%Y%m%d%H").timetuple())).isoformat()
'1998-07-20T12:00:00'
>>> sdb.from_array(np.array([time.mktime(datetime.strptime("1998072012", "%Y%m%d%H").timetuple())], dtype="int64")).apply("dt","datetime(f0)").project("dt").toarray()
array([numpy.datetime64('1998-07-20T12:00:00+0800')], dtype='datetime64[s]')
```

The resulting array now has value of '1998-07-20T12:00:00+0800', but I wanted '1998-07-20T12:00:00+0000', which is what the timestamp loaded into SciDB actually corresponds to.

The only workaround I found is to manually add a timezone offset to the timestamp loaded:

```
>>> sdb.from_array(np.array([time.mktime(datetime.strptime("1998072012", "%Y%m%d%H").timetuple()) + 28800], dtype="int64")).apply("dt","datetime(f0)").project("dt").toarray()
array([numpy.datetime64('1998-07-20T20:00:00+0800')], dtype='datetime64[s]')
```

Is there a convenient and direct way how to load datetime data (that have no time zone specified) into SciDB as SciDB's datetime?

**Comment by rvernica** [comment]
This has been fixed in SciDB-Py `16.9.1`. Here is an example:
```python
>>> db.create_array('taz', '<x:datetime not null>[i]')
>>> db.load('taz', upload_data=numpy.array([numpy.datetime64(datetime.strptime("1998072012", "%Y%m%d%H"), 's')]))
Array(DB('http://localhost:8080', None, None, None, None), 'taz')
>>> db.arrays.taz[:]
   i                   x
0  0 1998-07-20 12:00:00
```
Notice the use of `'s'` when creating the NumPy DateTime objects to force second precision.
