### ISSUE TITLE
remove_versions and create_array nested in store

### ISSUE THREAD

**Issue by rvernica** [Paradigm4/SciDB-Py#91]
`remove_versions` operator gets nested in `store` which is not correct. Here is an example:
```python
>>> scidbpy.__version__
u'15.12.dev1'
>>> sdb.random(10).remove_versions(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vernica/.local/lib/python2.7/site-packages/scidbpy/scidbarray.py", line 772, in __repr__
    show = self.interface._show_array(self.name, fmt='csv').split('\n')
  File "/home/vernica/.local/lib/python2.7/site-packages/scidbpy/interface.py", line 272, in _show_array
    result =  self._execute_query(query, **kwargs).replace('\\','')
  File "/home/vernica/.local/lib/python2.7/site-packages/scidbpy/interface.py", line 1746, in _execute_query
    release=False, **kwargs)
  File "/home/vernica/.local/lib/python2.7/site-packages/scidbpy/interface.py", line 1830, in _shim_execute_query
    result = self._shim_urlopen(url)
  File "/home/vernica/.local/lib/python2.7/site-packages/scidbpy/interface.py", line 1792, in _shim_urlopen
    raise Error(r.text)
scidbpy.errors.SciDBQueryError: UserQueryException in file: src/query/parser/Translator.cpp function: prohibitDdl line: 3644
Error id: scidb::SCIDB_SE_QPROC::SCIDB_LE_DDL_CANT_BE_NESTED
Error description: Query processor error. DDL operators cannot be nested.
store(remove_versions(py1478800993969831295_00318,1), py1478800993969831295_00319)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Should `remove_versions` be added to the `schema_utils` module? Or maybe the `store` step can be skipped with a flag? 

In the meantime, the obvious workaround is to use `query`.

**Comment by rvernica** [comment]
Same issue for `create_array`:
```python
>>> sdb.afl.create_array('foo', '<i:double>[j=0:9,10,0]', False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vernica/.local/lib/python2.7/site-packages/scidbpy/scidbarray.py", line 772, in __repr__
    show = self.interface._show_array(self.name, fmt='csv').split('\n')
  File "/home/vernica/.local/lib/python2.7/site-packages/scidbpy/interface.py", line 272, in _show_array
    result =  self._execute_query(query, **kwargs).replace('\\','')
  File "/home/vernica/.local/lib/python2.7/site-packages/scidbpy/interface.py", line 1746, in _execute_query
    release=False, **kwargs)
  File "/home/vernica/.local/lib/python2.7/site-packages/scidbpy/interface.py", line 1830, in _shim_execute_query
    result = self._shim_urlopen(url)
  File "/home/vernica/.local/lib/python2.7/site-packages/scidbpy/interface.py", line 1792, in _shim_urlopen
    raise Error(r.text)
scidbpy.errors.SciDBQueryError: UserQueryException in file: src/query/parser/Translator.cpp function: prohibitDdl line: 3644
Error id: scidb::SCIDB_SE_QPROC::SCIDB_LE_DDL_CANT_BE_NESTED
Error description: Query processor error. DDL operators cannot be nested.
store(create_array(foo,<i:double>[j=0:9,10,0],False), py1478800993969831295_00360)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by rvernica** [comment]
Turns out `store` can be easily avoided by appending `eval(store=False)`. For the examples above, it looks like:
```python
>>> sdb.random(10).remove_versions(1).eval(store=False)
>>> sdb.afl.create_array('foo', '<i:double>[j=0:9,10,0]', False).eval(store=False)
```
