### ISSUE TITLE
Support SciDB 16.9

### ISSUE THREAD

**Issue by rvernica** [Paradigm4/SciDB-Py#92]
The current `master` does not seem to work with SciDB `16.9`:
```
> curl http://localhost:8080/version
16.9.0% 
```
```
> pip install --user git+http://github.com/paradigm4/scidb-py.git
Collecting git+http://github.com/paradigm4/scidb-py.git
  Cloning http://github.com/paradigm4/scidb-py.git to /tmp/pip-CqC8DD-build
Installing collected packages: scidb-py
  Running setup.py install for scidb-py ... done
Successfully installed scidb-py-15.12.dev0
You are using pip version 8.0.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
```
> python
Python 2.7.12 (default, Sep 29 2016, 13:30:34) 
[GCC 6.2.1 20160916 (Red Hat 6.2.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from scidbpy import connect
>>> sdb = connect() 
.../.local/lib/python2.7/site-packages/scidbpy/parse.py:135: VisibleDeprecationWarning: converting an array with ndim > 0 to an index will result in an error in the future
  yield None if masked else contents[offset: offset + sz - 1].decode('utf-8')
.../.local/lib/python2.7/site-packages/scidbpy/parse.py:133: VisibleDeprecationWarning: converting an array with ndim > 0 to an index will result in an error in the future
  sz = np.fromstring(contents[offset: offset + 4], '<i')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../.local/lib/python2.7/site-packages/scidbpy/interface.py", line 1919, in connect
    result = SciDBShimInterface(url, user=username, password=password)
  File ".../.local/lib/python2.7/site-packages/scidbpy/interface.py", line 1706, in __init__
    self._refresh_afl()
  File ".../.local/lib/python2.7/site-packages/scidbpy/interface.py", line 1629, in _refresh_afl
    ops = [op for op, source in op_list]
TypeError: iteration over a 0-d array
>>> import scidbpy
>>> scidbpy.__version__
u'15.12.dev'
```

**Comment by apoliakov** [comment]
True - this needs to happen. Things are a bit busy right now, P4 staff may not get to this for another month or so.

**Comment by rvernica** [comment]
Thanks, @apoliakov. Do you have any high-level guidance on what needs to be done?

**Comment by apoliakov** [comment]
@rvernica 
Very likely parsing the show command properly. The 15.12 create array syntax is still supported in 16.9 but the output of `show` uses a new syntax: `dim=START:END:OVERLAP:CHUNK_SIZE`

This syntax was added in the spirit of making size optional, so you could specify start,end,overlap or start,end only. So Python likely needs to be taught to parse these:

```bash
$ iquery -aq "create array foo <val:double>[i=1:10,10,0]"    #it knows how to parse this
Query was executed successfully

$ iquery -aq "show(foo)"
{i} schema
{0} 'foo<val:double> [i=1:10:0:10]'   #it needs to parse this in 16.9
```

**Comment by rvernica** [comment]
Thanks! See PR #94 for changes to the new `16.9` syntax.

**Comment by rvernica** [comment]
#94 merged.
