### ISSUE TITLE
NumPy 1.12.0 TypeError: only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by rvernica** [Paradigm4/SciDB-Py#96]
With NumPy `1.11.0` a `VisibleDeprecationWarning` is dispalyed, with NumPy `1.12.0` it fails to connect.

#### NumPy `1.11.0`
```python
# python
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.11.0'
>>> import scidbpy
>>> scidbpy.connect()
scidbpy/parse.py:135: VisibleDeprecationWarning: converting an array with ndim > 0 to an index will result in an error in the future
  yield None if masked else contents[offset: offset + sz - 1].decode('utf-8')
scidbpy/parse.py:133: VisibleDeprecationWarning: converting an array with ndim > 0 to an index will result in an error in the future
  sz = np.fromstring(contents[offset: offset + 4], '<i')
<scidbpy.interface.SciDBShimInterface object at 0x7f11ad41a150>
```

#### NumPy `1.12.0`
```python
# python
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.12.0'
>>> import scidbpy
>>> scidbpy.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "scidbpy/interface.py", line 1919, in connect
    result = SciDBShimInterface(url, user=username, password=password)
  File "scidbpy/interface.py", line 1706, in __init__
    self._refresh_afl()
  File "scidbpy/interface.py", line 1626, in _refresh_afl
    op_list = self.afl.list("'operators'").toarray()   # query the connected SciDB engine to view the currently supported list of operators 
  File "scidbpy/scidbarray.py", line 999, in toarray
    return parse.toarray(self, **kwargs)
  File "scidbpy/parse.py", line 357, in toarray
    return func(array, compression=compression)
  File "scidbpy/parse.py", line 286, in toarray_sparse
    atts = _attribute_dict(unpacked, compression)
  File "scidbpy/parse.py", line 224, in _attribute_dict
    a = _string_attribute_dict(subarray, compression=compression)
  File "scidbpy/parse.py", line 155, in _string_attribute_dict
    result = np.array(list(_iter_strings(contents, nullable)), dtype=object)
  File "scidbpy/parse.py", line 135, in _iter_strings
    yield None if masked else contents[offset: offset + sz - 1].decode('utf-8')
TypeError: only integer scalar arrays can be converted to a scalar index
```

* SciDB `16.9`
* SciDB-Py [0afda10](https://github.com/Paradigm4/SciDB-Py/tree/0afda10aa7987a993496668094cdb68cd4141321)

**Comment by davidgutierrez** [comment]
Right Now im using SciDB and WFDB and WFDB  doesnt work with numpy 1.11, help!!
