### ISSUE TITLE
from_array fails on toarray if string attributes are present

### ISSUE THREAD

**Issue by rvernica** [Paradigm4/SciDB-Py#97]
If `from_array` is called with a result of `toarray`, it fails if the array contains string attributes. Here is an example:
```python
>>> sdb.from_array(sdb.afl.list().toarray())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "scidbpy/interface.py", line 925, in from_array
    arr = self.new_array(A.shape, A.dtype, chunk_size=chunk_size, **kwargs)
  File "scidbpy/interface.py", line 348, in new_array
    datashape = SciDBDataShape(shape, dtype, **kwargs)
  File "scidbpy/scidbarray.py", line 273, in __init__
    self.sdbtype = sdbtype(typecode)
  File "scidbpy/scidbarray.py", line 125, in __init__
    self.schema = self._dtype_to_schema(self.dtype)
  File "scidbpy/scidbarray.py", line 242, in _dtype_to_schema
    pairs = ["{0}:{1} NOT NULL".format(d[0], _sdb_type(d[1])) for d in dtype]
  File "scidbpy/scidbarray.py", line 64, in _sdb_type
    raise TypeError("Numpy dtype has no SciDB equivalent: %s" % np_type)
TypeError: Numpy dtype has no SciDB equivalent: |O
```
On the other hand, this works:
```
>>> sdb.afl.list().toarray() 
array([ ...
>>> sdb.from_array(sdb.afl.list().project('uaid', 'aid').toarray())
SciDBArray()
```
This might be related to #80 but notice that `from_dataframe` or Pandas are not used.

* SciDB `16.9`
* SciDB-Py [0afda10](https://github.com/Paradigm4/SciDB-Py/tree/0afda10aa7987a993496668094cdb68cd4141321)

**Comment by rvernica** [comment]
This has been fixed in SciDB-Py `16.9.1`. Here is an example:
```python
>>> data = db.list().fetch(as_dataframe=False, atts_only=True)
>>> schema = db.show("list()", "afl")[:]['schema'][0]
>>> schema = schema[schema.index('<'):]
>>> db.iquery(
      "input({sch}, '{fn}', 0, '{fmt}')", 
      upload_data=data, 
      upload_schema=scidbpy.schema.Schema.fromstring(schema))
```
